### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by ssx** [appersonlabs/segment.io#1]
Hi folks,

I've just attempted to use this module with 3.2.1 GA and I'm getting the following error on build:

[INFO] :   Invoking xcodebuild
[ERROR] :  *\* BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :   Ld build/Debug-iphonesimulator/Test\ App.app/Test\ App normal i386
[ERROR] :  (1 failure)

Any ideas?

**Comment by MohanLalKashyap** [comment]
I am also facing the same problem and any help will be appreciated
